<?php

namespace Mazzcris\OoStripePhp;

/**
 * @method getId()
 * @method getObject()
 * @method getApplication()
 * @method getApplicationFeePercent()
 * @method getAutomaticTax()
 * @method getBillingCycleAnchor()
 * @method getBillingThresholds()
 * @method getCancelAt()
 * @method getCancelAtPeriodEnd()
 * @method getCanceledAt()
 * @method getCancellationDetails()
 * @method getCollectionMethod()
 * @method getCreated()
 * @method getCurrency()
 * @method getCurrentPeriodEnd()
 * @method getCurrentPeriodStart()
 * @method getCustomer()
 * @method getDaysUntilDue()
 * @method getDefaultPaymentMethod()
 * @method getDefaultSource()
 * @method getDefaultTaxRates()
 * @method getDescription()
 * @method getDiscount()
 * @method getDiscounts()
 * @method getEndedAt()
 * @method getInvoiceSettings()
 * @method getItems()
 * @method getLatestInvoice()
 * @method getLivemode()
 * @method getMetadata()
 * @method getNextPendingInvoiceItemInvoice()
 * @method getOnBehalfOf()
 * @method getPauseCollection()
 * @method getPaymentSettings()
 * @method getPendingInvoiceItemInterval()
 * @method getPendingSetupIntent()
 * @method getPendingUpdate()
 * @method getSchedule()
 * @method getStartDate()
 * @method getStatus()
 * @method getTestClock()
 * @method getTransferData()
 * @method getTrialEnd()
 * @method getTrialSettings()
 * @method getTrialStart()
 */
class OoSubscription extends \Stripe\Subscription
{
    use DynamicGetterTrait;
}